### ISSUE TITLE
Collaboration Request

### ISSUE THREAD

**Issue by HarjjotSinghh** [Tailframes/react-components#3]
Hey @t-guzik , this is not a feature request but I want to contribute to this project as a collaborator, is there any way we can connect or any way I can contact you? I already checked your GitHub profile and @tailframes_Twitter handle for any contact information but could not find any details.
Please feel free to contact me here if you are interested in finding collaborators/contributors!

**Comment by t-guzik** [comment]
> Hey @t-guzik , this is not a feature request but I want to contribute to this project as a collaborator, is there any way we can connect or any way I can contact you? I already checked your GitHub profile and @tailframes_Twitter handle for any contact information but could not find any details. Please feel free to contact me here if you are interested in finding collaborators/contributors!

Hi @HarjjotSinghh, It is a great honor for us that you want to participate in our project. At the moment, we do not anticipate the possibility of expanding the team working on the development of Tailframes. However, we do not exclude that such a possibility will appear in the future. We encourage you to test our components and share your feedback with us. I hope we will stay in touch in the future. :

**Comment by HarjjotSinghh** [comment]
Alright, I will make sure to test out all the components in my upcoming projects and share my feedback! 
Thanks or your time!
